name: embedded_fl_dot_line_segment_painter
description: "Demo for fl_chart in Flutter with a custom FLDotLineSegmentPainter, embeddable in HTML."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
